## Project Scenario:

An international firm that is looking to expand its business in different countries across the world has recruited you. You have been hired as a junior Data Engineer and are tasked with creating a script that can extract the list of the top 10 largest economies of the world in descending order of their GDPs in Billion USD (rounded to 2 decimal places), as logged by the International Monetary Fund (IMF).

The required data seems to be available on the URL mentioned below:

URL: https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29

## Objectives

After completing this lab we will be able to:

 - Use Webscraping to extract required information from a website.
 - Use Pandas to load and process the tabular data as a dataframe.
 - Use Numpy to manipulate the information contatined in the dataframe.
 - Load the updated dataframe to CSV file.

In [8]:
#Install required packages
!pip install pandas numpy 
!pip install lxml

Requirement already satisfied: pandas in c:\users\ayush\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy in c:\users\ayush\anaconda3\lib\site-packages (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ayush\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ayush\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ayush\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\ayush\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: lxml in c:\users\ayush\anaconda3\lib\site-packages (5.2.1)

In [10]:
import numpy as np
import pandas as pd

# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

In [12]:
URL="https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

In [15]:
# Extracting tables from webpage using Pandas. Retain table number 3 as the required dataframe.
tables = pd.read_html(URL)
df = tables[3]

# Replaceing the column headers with column numbers
df.columns = range(df.shape[1])

# Retaining columns with index 0 and 2 (name of country and value of GDP quoted by IMF)
df = df[[0,2]]
# Retain the Rows with index 1 to 10, indicating the top 10 economies of the world.
df = df.iloc[1:11,:]
# Assigning column names as "Country" and "GDP (Million USD)"
df.columns = ['Country','GDP (Million USD)']

In [17]:

# Changing the data type of the 'GDP (Million USD)' column to integer. Use astype() method.
df['GDP (Million USD)'] = df['GDP (Million USD)'].astype(int)

# Convert the GDP value in Million USD to Billion USD
df['GDP (Million USD)'] = df['GDP (Million USD)']/1000
# Useing numpy.round() method to round the value to 2 decimal places.
df['GDP (Million USD)'] = np.round(df['GDP (Million USD)'] , 2)
# Renaming the column header from 'GDP (Million USD)' to 'GDP (Billion USD)'
df.rename(columns={'GDP (Millions USD)': 'GDP (Billions USD)'}, inplace = True)
df

           Country  GDP (Million USD)
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24